### PR TITLE
Feature-UI: Questions

### PR DESCRIPTION
**Pull request by rickynyairo**
**What does this PR do?**
Completes the questions page where users can access questions and the answers to those questions as well as post answers. 

**Description of tasks to be completed**
Allows a user to view all the questions in the system as well as their answers. A user can submit their own answer to a question. 

How should this be manually tested?
Clone or download the repository.
Navigate to the UI directory and open the index.html file on a browser. 
Default email and password:
-john_doe@gmail.com
-password
Alternatively, open questions.html.

What are the relevant Pivotal Tracker Stories?
[#159595443](https://www.pivotaltracker.com/story/show/159595443)

Screenshot:
questions

### CODE REVIEW

**Comment by asheux** [comment]
Nice descriptions.

**Comment by Enockkenya** [comment]
your pivotal tracker story ID  has a 404 error  good stuff though and well detailed description

**Comment by TheSteelGuy** [comment]
Nice one UI designs. However it is considered a bad practice to merge code to master if there is a likelihood that changes will be made to that code. Ie the code on the master branch is supposed to be final. So in future tasks always ensure you have a branch called develop or development which sits between your other branches and the master. Once you are sure you the code is final then you can merge from develop/development branch to master. Remember: **_branch A -> develop/development ->master and not Branch A>Master_**

**Comment by rickynyairo** [comment]
Thanks @Enockkenya Let me fix that

**Comment by mmosoroohh** [comment]
UI looks great and also good work on the PR

**Comment by rickynyairo** [comment]
Thanks @TheSteelGuy 
Very informative. I've made the changes.

**Comment by Tony-Ndichu** [comment]
Good job @rickynyairo  , maybe add abit more juice to the styling of the questions and answer texts and the form too. Also, having a background image on a main page like this could distract the user.

**Pull request merged**
